require 'spec/rake/spectask'

task :default => 'specs'

desc "Run all specs"
Spec::Rake::SpecTask.new('specs') do |t|
  t.spec_opts = ["--format", "specdoc", "--colour"]
  t.spec_files = Dir['spec/*_spec.rb'].sort
end